[pytest]
markers =
    smoke: маркер для дымовых тестов
    functional: маркер для функциональных тестов
    ui: маркер для тестов пользовательского интерфейса
    security: маркер для тестов безопасности
